// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: mikebway/cart/cart_api.proto

package cart

import (
	types "github.com/mikebway/poc-gcp-ecomm/pb/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request parameters for the CreateShoppingCart API
type CreateShoppingCartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The person / user requesting to open a new shopping cart
	Shopper *types.Person `protobuf:"bytes,1,opt,name=shopper,proto3" json:"shopper,omitempty"`
}

func (x *CreateShoppingCartRequest) Reset() {
	*x = CreateShoppingCartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mikebway_cart_cart_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateShoppingCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShoppingCartRequest) ProtoMessage() {}

func (x *CreateShoppingCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mikebway_cart_cart_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShoppingCartRequest.ProtoReflect.Descriptor instead.
func (*CreateShoppingCartRequest) Descriptor() ([]byte, []int) {
	return file_mikebway_cart_cart_api_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShoppingCartRequest) GetShopper() *types.Person {
	if x != nil {
		return x.Shopper
	}
	return nil
}

// Response parameters for the CreateShoppingCart API
type CreateShoppingCartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The empty cart requested
	Cart *ShoppingCart `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
}

func (x *CreateShoppingCartResponse) Reset() {
	*x = CreateShoppingCartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mikebway_cart_cart_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateShoppingCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShoppingCartResponse) ProtoMessage() {}

func (x *CreateShoppingCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mikebway_cart_cart_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShoppingCartResponse.ProtoReflect.Descriptor instead.
func (*CreateShoppingCartResponse) Descriptor() ([]byte, []int) {
	return file_mikebway_cart_cart_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShoppingCartResponse) GetCart() *ShoppingCart {
	if x != nil {
		return x.Cart
	}
	return nil
}

// Request parameters for the GetShoppingCartByID API
type GetShoppingCartByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CartId string `protobuf:"bytes,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
}

func (x *GetShoppingCartByIDRequest) Reset() {
	*x = GetShoppingCartByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mikebway_cart_cart_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShoppingCartByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShoppingCartByIDRequest) ProtoMessage() {}

func (x *GetShoppingCartByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mikebway_cart_cart_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShoppingCartByIDRequest.ProtoReflect.Descriptor instead.
func (*GetShoppingCartByIDRequest) Descriptor() ([]byte, []int) {
	return file_mikebway_cart_cart_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetShoppingCartByIDRequest) GetCartId() string {
	if x != nil {
		return x.CartId
	}
	return ""
}

// Response parameters for the GetShoppingCartByID API.
//
// The cart field shall be missing / empty if no match was wound for the given ID.
type GetShoppingCartByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cart *ShoppingCart `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
}

func (x *GetShoppingCartByIDResponse) Reset() {
	*x = GetShoppingCartByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mikebway_cart_cart_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShoppingCartByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShoppingCartByIDResponse) ProtoMessage() {}

func (x *GetShoppingCartByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mikebway_cart_cart_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShoppingCartByIDResponse.ProtoReflect.Descriptor instead.
func (*GetShoppingCartByIDResponse) Descriptor() ([]byte, []int) {
	return file_mikebway_cart_cart_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetShoppingCartByIDResponse) GetCart() *ShoppingCart {
	if x != nil {
		return x.Cart
	}
	return nil
}

// Request parameters for the AddItemToShoppingCart API
type AddItemToShoppingCartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ID of the cart that the item should be added too
	CartId string `protobuf:"bytes,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	// The item to be added to the shopping cart
	Item *CartItem `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *AddItemToShoppingCartRequest) Reset() {
	*x = AddItemToShoppingCartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mikebway_cart_cart_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddItemToShoppingCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemToShoppingCartRequest) ProtoMessage() {}

func (x *AddItemToShoppingCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mikebway_cart_cart_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemToShoppingCartRequest.ProtoReflect.Descriptor instead.
func (*AddItemToShoppingCartRequest) Descriptor() ([]byte, []int) {
	return file_mikebway_cart_cart_api_proto_rawDescGZIP(), []int{4}
}

func (x *AddItemToShoppingCartRequest) GetCartId() string {
	if x != nil {
		return x.CartId
	}
	return ""
}

func (x *AddItemToShoppingCartRequest) GetItem() *CartItem {
	if x != nil {
		return x.Item
	}
	return nil
}

// Response parameters for the AddItemToShoppingCart API
type AddItemToShoppingCartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The populated cart requested
	Cart *ShoppingCart `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
}

func (x *AddItemToShoppingCartResponse) Reset() {
	*x = AddItemToShoppingCartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mikebway_cart_cart_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddItemToShoppingCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemToShoppingCartResponse) ProtoMessage() {}

func (x *AddItemToShoppingCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mikebway_cart_cart_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemToShoppingCartResponse.ProtoReflect.Descriptor instead.
func (*AddItemToShoppingCartResponse) Descriptor() ([]byte, []int) {
	return file_mikebway_cart_cart_api_proto_rawDescGZIP(), []int{5}
}

func (x *AddItemToShoppingCartResponse) GetCart() *ShoppingCart {
	if x != nil {
		return x.Cart
	}
	return nil
}

// Request parameters for the RemoveItemFromShoppingCart API
type RemoveItemFromShoppingCartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ID of the cart that the item should be removed from
	CartId string `protobuf:"bytes,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	// The item to be removed from the shopping cart
	ItemId string `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
}

func (x *RemoveItemFromShoppingCartRequest) Reset() {
	*x = RemoveItemFromShoppingCartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mikebway_cart_cart_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveItemFromShoppingCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItemFromShoppingCartRequest) ProtoMessage() {}

func (x *RemoveItemFromShoppingCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mikebway_cart_cart_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItemFromShoppingCartRequest.ProtoReflect.Descriptor instead.
func (*RemoveItemFromShoppingCartRequest) Descriptor() ([]byte, []int) {
	return file_mikebway_cart_cart_api_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveItemFromShoppingCartRequest) GetCartId() string {
	if x != nil {
		return x.CartId
	}
	return ""
}

func (x *RemoveItemFromShoppingCartRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

// Response parameters for the RemoveItemFromShoppingCart API
type RemoveItemFromShoppingCartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The (slightly) depopulated cart
	Cart *ShoppingCart `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
}

func (x *RemoveItemFromShoppingCartResponse) Reset() {
	*x = RemoveItemFromShoppingCartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mikebway_cart_cart_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveItemFromShoppingCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItemFromShoppingCartResponse) ProtoMessage() {}

func (x *RemoveItemFromShoppingCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mikebway_cart_cart_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItemFromShoppingCartResponse.ProtoReflect.Descriptor instead.
func (*RemoveItemFromShoppingCartResponse) Descriptor() ([]byte, []int) {
	return file_mikebway_cart_cart_api_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveItemFromShoppingCartResponse) GetCart() *ShoppingCart {
	if x != nil {
		return x.Cart
	}
	return nil
}

// Request parameters for the SetDeliveryAddress API
type SetDeliveryAddressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The ID of the cart that the address should be added too
	CartId string `protobuf:"bytes,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
	// The address to be set into the order
	DeliveryAddress *types.PostalAddress `protobuf:"bytes,2,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
}

func (x *SetDeliveryAddressRequest) Reset() {
	*x = SetDeliveryAddressRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mikebway_cart_cart_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetDeliveryAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDeliveryAddressRequest) ProtoMessage() {}

func (x *SetDeliveryAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mikebway_cart_cart_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDeliveryAddressRequest.ProtoReflect.Descriptor instead.
func (*SetDeliveryAddressRequest) Descriptor() ([]byte, []int) {
	return file_mikebway_cart_cart_api_proto_rawDescGZIP(), []int{8}
}

func (x *SetDeliveryAddressRequest) GetCartId() string {
	if x != nil {
		return x.CartId
	}
	return ""
}

func (x *SetDeliveryAddressRequest) GetDeliveryAddress() *types.PostalAddress {
	if x != nil {
		return x.DeliveryAddress
	}
	return nil
}

// Response parameters for the SetDeliveryAddress API
type SetDeliveryAddressResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The populated cart requested
	Cart *ShoppingCart `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
}

func (x *SetDeliveryAddressResponse) Reset() {
	*x = SetDeliveryAddressResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mikebway_cart_cart_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetDeliveryAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDeliveryAddressResponse) ProtoMessage() {}

func (x *SetDeliveryAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mikebway_cart_cart_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDeliveryAddressResponse.ProtoReflect.Descriptor instead.
func (*SetDeliveryAddressResponse) Descriptor() ([]byte, []int) {
	return file_mikebway_cart_cart_api_proto_rawDescGZIP(), []int{9}
}

func (x *SetDeliveryAddressResponse) GetCart() *ShoppingCart {
	if x != nil {
		return x.Cart
	}
	return nil
}

// Request parameters for the CheckoutShoppingCart API
type CheckoutShoppingCartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CartId string `protobuf:"bytes,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
}

func (x *CheckoutShoppingCartRequest) Reset() {
	*x = CheckoutShoppingCartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mikebway_cart_cart_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckoutShoppingCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutShoppingCartRequest) ProtoMessage() {}

func (x *CheckoutShoppingCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mikebway_cart_cart_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutShoppingCartRequest.ProtoReflect.Descriptor instead.
func (*CheckoutShoppingCartRequest) Descriptor() ([]byte, []int) {
	return file_mikebway_cart_cart_api_proto_rawDescGZIP(), []int{10}
}

func (x *CheckoutShoppingCartRequest) GetCartId() string {
	if x != nil {
		return x.CartId
	}
	return ""
}

// Response parameters for the CheckoutShoppingCart API.
type CheckoutShoppingCartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cart *ShoppingCart `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
}

func (x *CheckoutShoppingCartResponse) Reset() {
	*x = CheckoutShoppingCartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mikebway_cart_cart_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckoutShoppingCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutShoppingCartResponse) ProtoMessage() {}

func (x *CheckoutShoppingCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mikebway_cart_cart_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutShoppingCartResponse.ProtoReflect.Descriptor instead.
func (*CheckoutShoppingCartResponse) Descriptor() ([]byte, []int) {
	return file_mikebway_cart_cart_api_proto_rawDescGZIP(), []int{11}
}

func (x *CheckoutShoppingCartResponse) GetCart() *ShoppingCart {
	if x != nil {
		return x.Cart
	}
	return nil
}

// Request parameters for the AbandonShoppingCart API
type AbandonShoppingCartRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CartId string `protobuf:"bytes,1,opt,name=cart_id,json=cartId,proto3" json:"cart_id,omitempty"`
}

func (x *AbandonShoppingCartRequest) Reset() {
	*x = AbandonShoppingCartRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mikebway_cart_cart_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbandonShoppingCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbandonShoppingCartRequest) ProtoMessage() {}

func (x *AbandonShoppingCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mikebway_cart_cart_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbandonShoppingCartRequest.ProtoReflect.Descriptor instead.
func (*AbandonShoppingCartRequest) Descriptor() ([]byte, []int) {
	return file_mikebway_cart_cart_api_proto_rawDescGZIP(), []int{12}
}

func (x *AbandonShoppingCartRequest) GetCartId() string {
	if x != nil {
		return x.CartId
	}
	return ""
}

// Response parameters for the AbandonShoppingCart API.
type AbandonShoppingCartResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cart *ShoppingCart `protobuf:"bytes,1,opt,name=cart,proto3" json:"cart,omitempty"`
}

func (x *AbandonShoppingCartResponse) Reset() {
	*x = AbandonShoppingCartResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mikebway_cart_cart_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AbandonShoppingCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbandonShoppingCartResponse) ProtoMessage() {}

func (x *AbandonShoppingCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mikebway_cart_cart_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbandonShoppingCartResponse.ProtoReflect.Descriptor instead.
func (*AbandonShoppingCartResponse) Descriptor() ([]byte, []int) {
	return file_mikebway_cart_cart_api_proto_rawDescGZIP(), []int{13}
}

func (x *AbandonShoppingCartResponse) GetCart() *ShoppingCart {
	if x != nil {
		return x.Cart
	}
	return nil
}

var File_mikebway_cart_cart_api_proto protoreflect.FileDescriptor

var file_mikebway_cart_cart_api_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6d, 0x69, 0x6b, 0x65, 0x62, 0x77, 0x61, 0x79, 0x2f, 0x63, 0x61, 0x72, 0x74, 0x2f,
	0x63, 0x61, 0x72, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04,
	0x63, 0x61, 0x72, 0x74, 0x1a, 0x18, 0x6d, 0x69, 0x6b, 0x65, 0x62, 0x77, 0x61, 0x79, 0x2f, 0x63,
	0x61, 0x72, 0x74, 0x2f, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c,
	0x6d, 0x69, 0x6b, 0x65, 0x62, 0x77, 0x61, 0x79, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x6d, 0x69,
	0x6b, 0x65, 0x62, 0x77, 0x61, 0x79, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x70, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4d, 0x0a, 0x19, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x07, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x69, 0x6b, 0x65, 0x62, 0x77,
	0x61, 0x79, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x52,
	0x07, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x65, 0x72, 0x22, 0x44, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x53, 0x68, 0x6f, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x52, 0x04, 0x63, 0x61, 0x72, 0x74, 0x22, 0x35,
	0x0a, 0x1a, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72,
	0x74, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x63, 0x61, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63,
	0x61, 0x72, 0x74, 0x49, 0x64, 0x22, 0x45, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69,
	0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x52, 0x04, 0x63, 0x61, 0x72, 0x74, 0x22, 0x5b, 0x0a, 0x1c,
	0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x54, 0x6f, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x63, 0x61, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63,
	0x61, 0x72, 0x74, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x43, 0x61, 0x72, 0x74, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x47, 0x0a, 0x1d, 0x41, 0x64, 0x64,
	0x49, 0x74, 0x65, 0x6d, 0x54, 0x6f, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61,
	0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x63, 0x61,
	0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e,
	0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x52, 0x04, 0x63, 0x61,
	0x72, 0x74, 0x22, 0x55, 0x0a, 0x21, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x49, 0x74, 0x65, 0x6d,
	0x46, 0x72, 0x6f, 0x6d, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x72, 0x74, 0x49, 0x64,
	0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x22, 0x4c, 0x0a, 0x22, 0x52, 0x65, 0x6d,
	0x6f, 0x76, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x68, 0x6f, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x26, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x63, 0x61, 0x72, 0x74, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72,
	0x74, 0x52, 0x04, 0x63, 0x61, 0x72, 0x74, 0x22, 0x7e, 0x0a, 0x19, 0x53, 0x65, 0x74, 0x44, 0x65,
	0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x61, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x72, 0x74, 0x49, 0x64, 0x12, 0x48, 0x0a,
	0x10, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x69, 0x6b, 0x65, 0x62, 0x77,
	0x61, 0x79, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x61, 0x6c, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x0f, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x44, 0x0a, 0x1a, 0x53, 0x65, 0x74, 0x44, 0x65,
	0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x52, 0x04, 0x63, 0x61, 0x72, 0x74, 0x22, 0x36, 0x0a,
	0x1b, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x63, 0x61, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63,
	0x61, 0x72, 0x74, 0x49, 0x64, 0x22, 0x46, 0x0a, 0x1c, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75,
	0x74, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x52, 0x04, 0x63, 0x61, 0x72, 0x74, 0x22, 0x35, 0x0a,
	0x1a, 0x41, 0x62, 0x61, 0x6e, 0x64, 0x6f, 0x6e, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67,
	0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63,
	0x61, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61,
	0x72, 0x74, 0x49, 0x64, 0x22, 0x45, 0x0a, 0x1b, 0x41, 0x62, 0x61, 0x6e, 0x64, 0x6f, 0x6e, 0x53,
	0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x43, 0x61, 0x72, 0x74, 0x52, 0x04, 0x63, 0x61, 0x72, 0x74, 0x32, 0xb3, 0x05, 0x0a, 0x07,
	0x43, 0x61, 0x72, 0x74, 0x41, 0x50, 0x49, 0x12, 0x59, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x12, 0x1f, 0x2e,
	0x63, 0x61, 0x72, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20,
	0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x68, 0x6f, 0x70,
	0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x5c, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x43, 0x61, 0x72, 0x74, 0x42, 0x79, 0x49, 0x44, 0x12, 0x20, 0x2e, 0x63, 0x61, 0x72, 0x74,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74,
	0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x63, 0x61,
	0x72, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61,
	0x72, 0x74, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x62, 0x0a, 0x15, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x54, 0x6f, 0x53, 0x68, 0x6f,
	0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x12, 0x22, 0x2e, 0x63, 0x61, 0x72, 0x74,
	0x2e, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x54, 0x6f, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69,
	0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e,
	0x63, 0x61, 0x72, 0x74, 0x2e, 0x41, 0x64, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x54, 0x6f, 0x53, 0x68,
	0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x71, 0x0a, 0x1a, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x49, 0x74,
	0x65, 0x6d, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61,
	0x72, 0x74, 0x12, 0x27, 0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x49, 0x74, 0x65, 0x6d, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67,
	0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x63, 0x61,
	0x72, 0x74, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x46, 0x72, 0x6f,
	0x6d, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x44, 0x65,
	0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1f, 0x2e,
	0x63, 0x61, 0x72, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20,
	0x2e, 0x63, 0x61, 0x72, 0x74, 0x2e, 0x53, 0x65, 0x74, 0x44, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72,
	0x79, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x5f, 0x0a, 0x14, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x53, 0x68,
	0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x12, 0x21, 0x2e, 0x63, 0x61, 0x72,
	0x74, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69,
	0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e,
	0x63, 0x61, 0x72, 0x74, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x6f, 0x75, 0x74, 0x53, 0x68, 0x6f,
	0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x5c, 0x0a, 0x13, 0x41, 0x62, 0x61, 0x6e, 0x64, 0x6f, 0x6e, 0x53, 0x68,
	0x6f, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x12, 0x20, 0x2e, 0x63, 0x61, 0x72,
	0x74, 0x2e, 0x41, 0x62, 0x61, 0x6e, 0x64, 0x6f, 0x6e, 0x53, 0x68, 0x6f, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x63,
	0x61, 0x72, 0x74, 0x2e, 0x41, 0x62, 0x61, 0x6e, 0x64, 0x6f, 0x6e, 0x53, 0x68, 0x6f, 0x70, 0x70,
	0x69, 0x6e, 0x67, 0x43, 0x61, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6d, 0x69, 0x6b, 0x65, 0x62, 0x77, 0x61, 0x79, 0x2f, 0x70, 0x6f, 0x63, 0x2d, 0x67, 0x63, 0x70,
	0x2d, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x61, 0x72, 0x74, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mikebway_cart_cart_api_proto_rawDescOnce sync.Once
	file_mikebway_cart_cart_api_proto_rawDescData = file_mikebway_cart_cart_api_proto_rawDesc
)

func file_mikebway_cart_cart_api_proto_rawDescGZIP() []byte {
	file_mikebway_cart_cart_api_proto_rawDescOnce.Do(func() {
		file_mikebway_cart_cart_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_mikebway_cart_cart_api_proto_rawDescData)
	})
	return file_mikebway_cart_cart_api_proto_rawDescData
}

var file_mikebway_cart_cart_api_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_mikebway_cart_cart_api_proto_goTypes = []interface{}{
	(*CreateShoppingCartRequest)(nil),          // 0: cart.CreateShoppingCartRequest
	(*CreateShoppingCartResponse)(nil),         // 1: cart.CreateShoppingCartResponse
	(*GetShoppingCartByIDRequest)(nil),         // 2: cart.GetShoppingCartByIDRequest
	(*GetShoppingCartByIDResponse)(nil),        // 3: cart.GetShoppingCartByIDResponse
	(*AddItemToShoppingCartRequest)(nil),       // 4: cart.AddItemToShoppingCartRequest
	(*AddItemToShoppingCartResponse)(nil),      // 5: cart.AddItemToShoppingCartResponse
	(*RemoveItemFromShoppingCartRequest)(nil),  // 6: cart.RemoveItemFromShoppingCartRequest
	(*RemoveItemFromShoppingCartResponse)(nil), // 7: cart.RemoveItemFromShoppingCartResponse
	(*SetDeliveryAddressRequest)(nil),          // 8: cart.SetDeliveryAddressRequest
	(*SetDeliveryAddressResponse)(nil),         // 9: cart.SetDeliveryAddressResponse
	(*CheckoutShoppingCartRequest)(nil),        // 10: cart.CheckoutShoppingCartRequest
	(*CheckoutShoppingCartResponse)(nil),       // 11: cart.CheckoutShoppingCartResponse
	(*AbandonShoppingCartRequest)(nil),         // 12: cart.AbandonShoppingCartRequest
	(*AbandonShoppingCartResponse)(nil),        // 13: cart.AbandonShoppingCartResponse
	(*types.Person)(nil),                       // 14: mikebway.types.Person
	(*ShoppingCart)(nil),                       // 15: cart.ShoppingCart
	(*CartItem)(nil),                           // 16: cart.CartItem
	(*types.PostalAddress)(nil),                // 17: mikebway.types.PostalAddress
}
var file_mikebway_cart_cart_api_proto_depIdxs = []int32{
	14, // 0: cart.CreateShoppingCartRequest.shopper:type_name -> mikebway.types.Person
	15, // 1: cart.CreateShoppingCartResponse.cart:type_name -> cart.ShoppingCart
	15, // 2: cart.GetShoppingCartByIDResponse.cart:type_name -> cart.ShoppingCart
	16, // 3: cart.AddItemToShoppingCartRequest.item:type_name -> cart.CartItem
	15, // 4: cart.AddItemToShoppingCartResponse.cart:type_name -> cart.ShoppingCart
	15, // 5: cart.RemoveItemFromShoppingCartResponse.cart:type_name -> cart.ShoppingCart
	17, // 6: cart.SetDeliveryAddressRequest.delivery_address:type_name -> mikebway.types.PostalAddress
	15, // 7: cart.SetDeliveryAddressResponse.cart:type_name -> cart.ShoppingCart
	15, // 8: cart.CheckoutShoppingCartResponse.cart:type_name -> cart.ShoppingCart
	15, // 9: cart.AbandonShoppingCartResponse.cart:type_name -> cart.ShoppingCart
	0,  // 10: cart.CartAPI.CreateShoppingCart:input_type -> cart.CreateShoppingCartRequest
	2,  // 11: cart.CartAPI.GetShoppingCartByID:input_type -> cart.GetShoppingCartByIDRequest
	4,  // 12: cart.CartAPI.AddItemToShoppingCart:input_type -> cart.AddItemToShoppingCartRequest
	6,  // 13: cart.CartAPI.RemoveItemFromShoppingCart:input_type -> cart.RemoveItemFromShoppingCartRequest
	8,  // 14: cart.CartAPI.SetDeliveryAddress:input_type -> cart.SetDeliveryAddressRequest
	10, // 15: cart.CartAPI.CheckoutShoppingCart:input_type -> cart.CheckoutShoppingCartRequest
	12, // 16: cart.CartAPI.AbandonShoppingCart:input_type -> cart.AbandonShoppingCartRequest
	1,  // 17: cart.CartAPI.CreateShoppingCart:output_type -> cart.CreateShoppingCartResponse
	3,  // 18: cart.CartAPI.GetShoppingCartByID:output_type -> cart.GetShoppingCartByIDResponse
	5,  // 19: cart.CartAPI.AddItemToShoppingCart:output_type -> cart.AddItemToShoppingCartResponse
	7,  // 20: cart.CartAPI.RemoveItemFromShoppingCart:output_type -> cart.RemoveItemFromShoppingCartResponse
	9,  // 21: cart.CartAPI.SetDeliveryAddress:output_type -> cart.SetDeliveryAddressResponse
	11, // 22: cart.CartAPI.CheckoutShoppingCart:output_type -> cart.CheckoutShoppingCartResponse
	13, // 23: cart.CartAPI.AbandonShoppingCart:output_type -> cart.AbandonShoppingCartResponse
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_mikebway_cart_cart_api_proto_init() }
func file_mikebway_cart_cart_api_proto_init() {
	if File_mikebway_cart_cart_api_proto != nil {
		return
	}
	file_mikebway_cart_cart_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_mikebway_cart_cart_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateShoppingCartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mikebway_cart_cart_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateShoppingCartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mikebway_cart_cart_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShoppingCartByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mikebway_cart_cart_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShoppingCartByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mikebway_cart_cart_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddItemToShoppingCartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mikebway_cart_cart_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddItemToShoppingCartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mikebway_cart_cart_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveItemFromShoppingCartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mikebway_cart_cart_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveItemFromShoppingCartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mikebway_cart_cart_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetDeliveryAddressRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mikebway_cart_cart_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetDeliveryAddressResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mikebway_cart_cart_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckoutShoppingCartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mikebway_cart_cart_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckoutShoppingCartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mikebway_cart_cart_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AbandonShoppingCartRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mikebway_cart_cart_api_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AbandonShoppingCartResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mikebway_cart_cart_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mikebway_cart_cart_api_proto_goTypes,
		DependencyIndexes: file_mikebway_cart_cart_api_proto_depIdxs,
		MessageInfos:      file_mikebway_cart_cart_api_proto_msgTypes,
	}.Build()
	File_mikebway_cart_cart_api_proto = out.File
	file_mikebway_cart_cart_api_proto_rawDesc = nil
	file_mikebway_cart_cart_api_proto_goTypes = nil
	file_mikebway_cart_cart_api_proto_depIdxs = nil
}
